### ISSUE TITLE
servicelog does not build due to missing build dependency: librtas-devel

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/servicelog#1]
When building HostOS packages, servicelog failed to build due to missing librtas-devel package.

```
DEBUG: /bin/sh ./libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-swi
tches   -m64 -mcpu=power8 -mtune=power8  -Wl,-z,relro  -o src/servicelog_notify src/servicelog_notify.o src/platform.o -lservicelog -lsqlite3 
DEBUG: *** Warning: Linking the executable src/servicelog against the loadable module
DEBUG: *** libservicelog.so is not portable!
DEBUG: libtool: link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mcpu=power8 -mtu
ne=power8 -Wl,-z -Wl,relro -o src/servicelog src/servicelog_switch.o src/platform.o  /usr/lib64/libservicelog.so -lrtas -lrtasevent -lsqlite3
DEBUG: *** Warning: Linking the executable src/v1_servicelog against the loadable module
DEBUG: *** libservicelog.so is not portable!
DEBUG: /usr/bin/ld: cannot find -lrtas
DEBUG: /usr/bin/ld: cannot find -lrtasevent
DEBUG: collect2: error: ld returned 1 exit status
DEBUG: make: *** [src/servicelog] Error 1
DEBUG: make: *** Waiting for unfinished jobs....
DEBUG: *** Warning: Linking the executable src/v29_servicelog against the loadable module
DEBUG: *** libservicelog.so is not portable!
DEBUG: libtool: link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mcpu=power8 -mtu
ne=power8 -Wl,-z -Wl,relro -o src/v1_servicelog src/servicelog.o src/platform.o  /usr/lib64/libservicelog.so -lrtas -lrtasevent -lsqlite3
DEBUG: libtool: link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mcpu=power8 -mtu
ne=power8 -Wl,-z -Wl,relro -o src/v29_servicelog src/v29_servicelog.o src/platform.o  /usr/lib64/libservicelog.so -lrtas -lrtasevent -lsqlite3
DEBUG: /usr/bin/ld: cannot find -lrtas
DEBUG: /usr/bin/ld: cannot find -lrtasevent
DEBUG: collect2: error: ld returned 1 exit status
DEBUG: make: *** [src/v1_servicelog] Error 1
DEBUG: /usr/bin/ld: cannot find -lrtas
DEBUG: /usr/bin/ld: cannot find -lrtasevent
DEBUG: collect2: error: ld returned 1 exit status
DEBUG: make: *** [src/v29_servicelog] Error 1
DEBUG: *** Warning: Linking the executable src/servicelog_notify against the loadable module
DEBUG: *** libservicelog.so is not portable!
DEBUG: libtool: link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mcpu=power8 -mtu
ne=power8 -Wl,-z -Wl,relro -o src/servicelog_notify src/servicelog_notify.o src/platform.o  /usr/lib64/libservicelog.so -lrtas -lrtasevent -lsqlite3
DEBUG: /usr/bin/ld: cannot find -lrtas
DEBUG: /usr/bin/ld: cannot find -lrtasevent
DEBUG: collect2: error: ld returned 1 exit status
DEBUG: make: *** [src/servicelog_notify] Error 1
```

<cde:info> Mirrored with LTC bug #157951 </cde:info>

**Comment by mopsfelder** [comment]
We were able to work this around on HostOS side by adding librtas package as a build dependency for servicelog package. See https://github.com/open-power-host-os/versions/blob/master/servicelog/CentOS/7/servicelog.spec#L18

**Comment by hegdevasant** [comment]
Thanks for the workaround. I'm on vacation. Will look into it next week.

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-08-23 22:53:20 EDT-------
(In reply to comment #3)
&gt;
&gt; Thanks for the workaround. I'm on vacation. Will look into it next week.
&gt; 
&gt; -Vasant

I did quick verification on my mock environment. I'm not hitting this issue. 

Also servicelog is not directly depends on librtas. It has indirect dependency (servicelog -&gt; libservicelog -&gt; librtas).

So adding librtas as dependency is fine. 

-Vasant

**Comment by mopsfelder** [comment]
https://github.com/open-power-host-os/libservicelog/blob/hostos-devel/libservicelog.spec.in#L14 lists librtas-devel as a build-time dependency. I'm not sure if mock pulls it when creating a fresh environment. Otherwise we should not see this issue.

Since servicelog clearly needs librtas during build time, I think it's good to have it listed as BuildRequires explicitly.

(Side note: Get out of the computer and enjoy your vacation! :))

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-08-28 12:14:54 EDT-------
(In reply to comment #5)
&gt;
&gt; https://github.com/open-power-host-os/libservicelog/blob/hostos-devel/
&gt; libservicelog.spec.in#L14 lists librtas-devel as a build-time dependency.
&gt; I'm not sure if mock pulls it when creating a fresh environment. Otherwise
&gt; we should not see this issue.

Correct. libservicelog depends on librtas. (servicelog -&gt; libservicelog -&gt; librtas). But servicelog doesn't depend on librtas directly.

Hence ideally it should work fine without `librtas`  dependency. 

&gt; 
&gt; Since servicelog clearly needs librtas during build time, I think it's good
&gt; to have it listed as BuildRequires explicitly.

No. servicelog doesn't refer librtas directly. hence it shouldn't create build dependency.

But if it solves current issue then fine to add BuildRequires (anyway libservicelog also needs librtas).

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2017-12-07 05:57:31 EDT-------
Pushed changes to HostOS devel branch and release branch.

-Vasant
